// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AdditionalBandwidthUpdateRequest additional bandwidth update request
//
// swagger:model AdditionalBandwidthUpdateRequest
type AdditionalBandwidthUpdateRequest struct {

	// Additional bandwidth to be configured on virtual device
	// Required: true
	AdditionalBandwidth *int32 `json:"additionalBandwidth"`
}

// Validate validates this additional bandwidth update request
func (m *AdditionalBandwidthUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdditionalBandwidth(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdditionalBandwidthUpdateRequest) validateAdditionalBandwidth(formats strfmt.Registry) error {

	if err := validate.Required("additionalBandwidth", "body", m.AdditionalBandwidth); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AdditionalBandwidthUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdditionalBandwidthUpdateRequest) UnmarshalBinary(b []byte) error {
	var res AdditionalBandwidthUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
