// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgreementAcceptRequest agreement accept request
//
// swagger:model AgreementAcceptRequest
type AgreementAcceptRequest struct {

	// account number
	AccountNumber string `json:"accountNumber,omitempty"`

	// apttus Id
	ApttusID string `json:"apttusId,omitempty"`
}

// Validate validates this agreement accept request
func (m *AgreementAcceptRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgreementAcceptRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgreementAcceptRequest) UnmarshalBinary(b []byte) error {
	var res AgreementAcceptRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
