// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgreementStatusResponse agreement status response
//
// swagger:model AgreementStatusResponse
type AgreementStatusResponse struct {

	// error message
	ErrorMessage string `json:"errorMessage,omitempty"`

	// is valid
	IsValid string `json:"isValid,omitempty"`

	// terms
	Terms string `json:"terms,omitempty"`

	// terms version ID
	TermsVersionID string `json:"termsVersionID,omitempty"`
}

// Validate validates this agreement status response
func (m *AgreementStatusResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgreementStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgreementStatusResponse) UnmarshalBinary(b []byte) error {
	var res AgreementStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
