// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgreementAcceptResponse agreement accept response
//
// swagger:model AgreementAcceptResponse
type AgreementAcceptResponse struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this agreement accept response
func (m *AgreementAcceptResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgreementAcceptResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgreementAcceptResponse) UnmarshalBinary(b []byte) error {
	var res AgreementAcceptResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
