// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BgpUpdateRequest bgp update request
//
// swagger:model BgpUpdateRequest
type BgpUpdateRequest struct {

	// Authentication Key
	AuthenticationKey string `json:"authenticationKey,omitempty"`

	// Local ASN
	LocalAsn int64 `json:"localAsn,omitempty"`

	// Local IP Address with subnet
	LocalIPAddress string `json:"localIpAddress,omitempty"`

	// Remote ASN
	RemoteAsn int64 `json:"remoteAsn,omitempty"`

	// Remote IP Address
	RemoteIPAddress string `json:"remoteIpAddress,omitempty"`
}

// Validate validates this bgp update request
func (m *BgpUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BgpUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BgpUpdateRequest) UnmarshalBinary(b []byte) error {
	var res BgpUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
