// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BgpConfigAddRequest bgp config add request
//
// swagger:model BgpConfigAddRequest
type BgpConfigAddRequest struct {

	// Provide a key value that you can use later to authenticate.
	AuthenticationKey string `json:"authenticationKey,omitempty"`

	// UUID of the connection between the virtual device and the cloud service provider
	ConnectionUUID string `json:"connectionUUID,omitempty"`

	// Local ASN (autonomous system network). This is the ASN of the virtual device.
	LocalAsn int64 `json:"localAsn,omitempty"`

	// Local IP Address. This is the IP address of the virtual device in CIDR format.
	LocalIPAddress string `json:"localIpAddress,omitempty"`

	// Remote ASN (autonomous system network). This is the ASN of the cloud service provider.
	RemoteAsn int64 `json:"remoteAsn,omitempty"`

	// Remote IP Address. This is the IP address of the cloud service provider.
	RemoteIPAddress string `json:"remoteIpAddress,omitempty"`
}

// Validate validates this bgp config add request
func (m *BgpConfigAddRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BgpConfigAddRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BgpConfigAddRequest) UnmarshalBinary(b []byte) error {
	var res BgpConfigAddRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
