// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BgpInfo bgp info
//
// swagger:model BgpInfo
type BgpInfo struct {

	// authentication key
	AuthenticationKey string `json:"authenticationKey,omitempty"`

	// connection UUID
	ConnectionUUID string `json:"connectionUUID,omitempty"`

	// created by
	CreatedBy string `json:"createdBy,omitempty"`

	// created by email
	CreatedByEmail string `json:"createdByEmail,omitempty"`

	// created by full name
	CreatedByFullName string `json:"createdByFullName,omitempty"`

	// created date
	CreatedDate string `json:"createdDate,omitempty"`

	// deleted by
	DeletedBy string `json:"deletedBy,omitempty"`

	// deleted by email
	DeletedByEmail string `json:"deletedByEmail,omitempty"`

	// deleted by full name
	DeletedByFullName string `json:"deletedByFullName,omitempty"`

	// deleted date
	DeletedDate string `json:"deletedDate,omitempty"`

	// last updated by
	LastUpdatedBy string `json:"lastUpdatedBy,omitempty"`

	// last updated by email
	LastUpdatedByEmail string `json:"lastUpdatedByEmail,omitempty"`

	// last updated by full name
	LastUpdatedByFullName string `json:"lastUpdatedByFullName,omitempty"`

	// last updated date
	LastUpdatedDate string `json:"lastUpdatedDate,omitempty"`

	// local asn
	LocalAsn int64 `json:"localAsn,omitempty"`

	// local Ip address
	LocalIPAddress string `json:"localIpAddress,omitempty"`

	// provisioning status
	ProvisioningStatus string `json:"provisioningStatus,omitempty"`

	// remote asn
	RemoteAsn int64 `json:"remoteAsn,omitempty"`

	// remote Ip address
	RemoteIPAddress string `json:"remoteIpAddress,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`

	// virtual device UUID
	VirtualDeviceUUID string `json:"virtualDeviceUUID,omitempty"`
}

// Validate validates this bgp info
func (m *BgpInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BgpInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BgpInfo) UnmarshalBinary(b []byte) error {
	var res BgpInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
