// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ChainingDeviceInfo Unique Id of the device.
//
// swagger:model ChainingDeviceInfo
type ChainingDeviceInfo struct {

	// ASN number. The request will fail if you provide a new ASN for a device that already has an ASN.
	Asn int64 `json:"asn,omitempty"`

	// device
	// Required: true
	DeviceUUID *string `json:"deviceUUID"`
}

// Validate validates this chaining device info
func (m *ChainingDeviceInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceUUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChainingDeviceInfo) validateDeviceUUID(formats strfmt.Registry) error {

	if err := validate.Required("deviceUUID", "body", m.DeviceUUID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChainingDeviceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChainingDeviceInfo) UnmarshalBinary(b []byte) error {
	var res ChainingDeviceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
