// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChainingGroupNameSubnetPatchRequest chaining group name subnet patch request
//
// swagger:model ChainingGroupNameSubnetPatchRequest
type ChainingGroupNameSubnetPatchRequest struct {

	// Device linking group name.
	GroupName string `json:"groupName,omitempty"`

	// Subnet of the linking group.
	Subnet string `json:"subnet,omitempty"`
}

// Validate validates this chaining group name subnet patch request
func (m *ChainingGroupNameSubnetPatchRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChainingGroupNameSubnetPatchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChainingGroupNameSubnetPatchRequest) UnmarshalBinary(b []byte) error {
	var res ChainingGroupNameSubnetPatchRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
