// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ChainingGroupMetroThroughputInfo chaining group metro throughput info
//
// swagger:model ChainingGroupMetroThroughputInfo
type ChainingGroupMetroThroughputInfo struct {

	// Metro code.
	// Required: true
	MetroCode *string `json:"metroCode"`

	// Throughput.
	Throughput string `json:"throughput,omitempty"`

	// Throughput unit.
	ThroughputUnit string `json:"throughputUnit,omitempty"`
}

// Validate validates this chaining group metro throughput info
func (m *ChainingGroupMetroThroughputInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetroCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChainingGroupMetroThroughputInfo) validateMetroCode(formats strfmt.Registry) error {

	if err := validate.Required("metroCode", "body", m.MetroCode); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChainingGroupMetroThroughputInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChainingGroupMetroThroughputInfo) UnmarshalBinary(b []byte) error {
	var res ChainingGroupMetroThroughputInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
