// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Charges charges
//
// swagger:model Charges
type Charges struct {

	// Description of the charge, whether it is for the virtual device, the device license, or the additional bandwidth
	Description string `json:"description,omitempty"`

	// Monthly charges
	MonthlyRecurringCharges string `json:"monthlyRecurringCharges,omitempty"`
}

// Validate validates this charges
func (m *Charges) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Charges) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Charges) UnmarshalBinary(b []byte) error {
	var res Charges
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
