// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectionList connection list
//
// swagger:model ConnectionList
type ConnectionList struct {

	// interface Uuid
	InterfaceUUID string `json:"interfaceUuid,omitempty"`

	// is primary
	IsPrimary bool `json:"isPrimary,omitempty"`

	// metro
	Metro string `json:"metro,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// redundant connection
	RedundantConnection *ConnectionList `json:"redundantConnection,omitempty"`

	// redundant Uuid
	RedundantUUID string `json:"redundantUuid,omitempty"`

	// seller organization name
	SellerOrganizationName string `json:"sellerOrganizationName,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this connection list
func (m *ConnectionList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRedundantConnection(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConnectionList) validateRedundantConnection(formats strfmt.Registry) error {

	if swag.IsZero(m.RedundantConnection) { // not required
		return nil
	}

	if m.RedundantConnection != nil {
		if err := m.RedundantConnection.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("redundantConnection")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConnectionList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectionList) UnmarshalBinary(b []byte) error {
	var res ConnectionList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
