// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CustomerInfo customer info
//
// swagger:model CustomerInfo
type CustomerInfo struct {

	// City
	City string `json:"city,omitempty"`

	// Country
	Country string `json:"country,omitempty"`

	// Customer name
	Name string `json:"name,omitempty"`

	// Postal code
	PostalCode string `json:"postalCode,omitempty"`

	// State
	State string `json:"state,omitempty"`

	// Street
	Street string `json:"street,omitempty"`
}

// Validate validates this customer info
func (m *CustomerInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomerInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomerInfo) UnmarshalBinary(b []byte) error {
	var res CustomerInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
