// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceChainingGroupResponse device chaining group response
//
// swagger:model DeviceChainingGroupResponse
type DeviceChainingGroupResponse struct {

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this device chaining group response
func (m *DeviceChainingGroupResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceChainingGroupResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceChainingGroupResponse) UnmarshalBinary(b []byte) error {
	var res DeviceChainingGroupResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
