// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceElement device element
//
// swagger:model DeviceElement
type DeviceElement struct {

	// description
	Description string `json:"description,omitempty"`

	// monthly recurring charges
	MonthlyRecurringCharges float64 `json:"monthlyRecurringCharges,omitempty"`

	// non recurring charges
	NonRecurringCharges float64 `json:"nonRecurringCharges,omitempty"`

	// product code
	ProductCode string `json:"productCode,omitempty"`
}

// Validate validates this device element
func (m *DeviceElement) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceElement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceElement) UnmarshalBinary(b []byte) error {
	var res DeviceElement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
