// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetValidateAuthkeyresPrimary get validate authkeyres primary
//
// swagger:model GetValidateAuthkeyresPrimary
type GetValidateAuthkeyresPrimary struct {

	// bandwidth
	Bandwidth string `json:"bandwidth,omitempty"`
}

// Validate validates this get validate authkeyres primary
func (m *GetValidateAuthkeyresPrimary) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetValidateAuthkeyresPrimary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetValidateAuthkeyresPrimary) UnmarshalBinary(b []byte) error {
	var res GetValidateAuthkeyresPrimary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
