// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LicenseUploadResponse license upload response
//
// swagger:model LicenseUploadResponse
type LicenseUploadResponse struct {

	// file Id
	FileID string `json:"fileId,omitempty"`
}

// Validate validates this license upload response
func (m *LicenseUploadResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LicenseUploadResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LicenseUploadResponse) UnmarshalBinary(b []byte) error {
	var res LicenseUploadResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
