// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LicenseFileMappingDto license file mapping dto
//
// swagger:model LicenseFileMappingDto
type LicenseFileMappingDto struct {

	// filename
	Filename string `json:"filename,omitempty"`

	// throughput
	Throughput int32 `json:"throughput,omitempty"`

	// throughput unit
	ThroughputUnit string `json:"throughputUnit,omitempty"`
}

// Validate validates this license file mapping dto
func (m *LicenseFileMappingDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LicenseFileMappingDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LicenseFileMappingDto) UnmarshalBinary(b []byte) error {
	var res LicenseFileMappingDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
