// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LicenseOptions license options
//
// swagger:model LicenseOptions
type LicenseOptions struct {

	// License name
	Name string `json:"name,omitempty"`

	// License type
	Type string `json:"type,omitempty"`
}

// Validate validates this license options
func (m *LicenseOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LicenseOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LicenseOptions) UnmarshalBinary(b []byte) error {
	var res LicenseOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
