// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetroAccountResponse metro account response
//
// swagger:model MetroAccountResponse
type MetroAccountResponse struct {

	// account Name
	AccountName string `json:"accountName,omitempty"`

	// account number
	AccountNumber int64 `json:"accountNumber,omitempty"`

	// account status
	AccountStatus string `json:"accountStatus,omitempty"`

	// account UcmId
	AccountUcmID string `json:"accountUcmId,omitempty"`

	// referenceId
	ReferenceID string `json:"referenceId,omitempty"`
}

// Validate validates this metro account response
func (m *MetroAccountResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetroAccountResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetroAccountResponse) UnmarshalBinary(b []byte) error {
	var res MetroAccountResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
