// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetroStatus metro status
//
// swagger:model MetroStatus
type MetroStatus struct {

	// created
	Created bool `json:"created,omitempty"`

	// device to Ip map
	DeviceToIPMap map[string]string `json:"deviceToIpMap,omitempty"`

	// error code
	ErrorCode string `json:"errorCode,omitempty"`

	// error message
	ErrorMessage string `json:"errorMessage,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this metro status
func (m *MetroStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetroStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetroStatus) UnmarshalBinary(b []byte) error {
	var res MetroStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
