// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Metro metro
//
// swagger:model Metro
type Metro struct {

	// Metro code
	MetroCode string `json:"metroCode,omitempty"`

	// Metro description
	MetroDescription string `json:"metroDescription,omitempty"`

	// Region. It may have several metros.
	Region string `json:"region,omitempty"`
}

// Validate validates this metro
func (m *Metro) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Metro) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Metro) UnmarshalBinary(b []byte) error {
	var res Metro
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
