// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OptionalService optional service
//
// swagger:model OptionalService
type OptionalService struct {

	// name
	Name string `json:"name,omitempty"`

	// service code
	ServiceCode string `json:"serviceCode,omitempty"`
}

// Validate validates this optional service
func (m *OptionalService) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OptionalService) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OptionalService) UnmarshalBinary(b []byte) error {
	var res OptionalService
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
