// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderTermsResponse order terms response
//
// swagger:model OrderTermsResponse
type OrderTermsResponse struct {

	// terms
	Terms string `json:"terms,omitempty"`
}

// Validate validates this order terms response
func (m *OrderTermsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderTermsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderTermsResponse) UnmarshalBinary(b []byte) error {
	var res OrderTermsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
