// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PageResponseDtoMetroAccountResponse page response dto metro account response
//
// swagger:model PageResponseDto-MetroAccountResponse
type PageResponseDtoMetroAccountResponse struct {

	// accountCreateUrl
	AccountCreateURL string `json:"accountCreateUrl,omitempty"`

	// content
	Content []*MetroAccountResponse `json:"content"`

	// error Code
	ErrorCode string `json:"errorCode,omitempty"`

	// error Message
	ErrorMessage string `json:"errorMessage,omitempty"`

	// Total count
	TotalCount int64 `json:"totalCount,omitempty"`
}

// Validate validates this page response dto metro account response
func (m *PageResponseDtoMetroAccountResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PageResponseDtoMetroAccountResponse) validateContent(formats strfmt.Registry) error {

	if swag.IsZero(m.Content) { // not required
		return nil
	}

	for i := 0; i < len(m.Content); i++ {
		if swag.IsZero(m.Content[i]) { // not required
			continue
		}

		if m.Content[i] != nil {
			if err := m.Content[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("content" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PageResponseDtoMetroAccountResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PageResponseDtoMetroAccountResponse) UnmarshalBinary(b []byte) error {
	var res PageResponseDtoMetroAccountResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
