// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecondaryDeviceDeleteRequest secondary device delete request
//
// swagger:model SecondaryDeviceDeleteRequest
type SecondaryDeviceDeleteRequest struct {

	// Object that holds the secondary deactivation key for HA (high availability) devices.
	DeactivationKey string `json:"deactivationKey,omitempty"`
}

// Validate validates this secondary device delete request
func (m *SecondaryDeviceDeleteRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecondaryDeviceDeleteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecondaryDeviceDeleteRequest) UnmarshalBinary(b []byte) error {
	var res SecondaryDeviceDeleteRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
