// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SSHUsers ssh users
//
// swagger:model sshUsers
type SSHUsers struct {

	// action
	Action string `json:"action,omitempty"`

	// sshPassword
	SSHPassword string `json:"sshPassword,omitempty"`

	// sshUserUuid
	SSHUserUUID string `json:"sshUserUuid,omitempty"`

	// sshUsername. This should be minimum 3 and maximum 32 characters and include alphanumeric characters, dash, and underscore.
	SSHUsername string `json:"sshUsername,omitempty"`
}

// Validate validates this ssh users
func (m *SSHUsers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SSHUsers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SSHUsers) UnmarshalBinary(b []byte) error {
	var res SSHUsers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
