// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SSHUsersBulkOperationsRequest Ssh users bulk operations request
//
// swagger:model SshUsersBulkOperationsRequest
type SSHUsersBulkOperationsRequest struct {

	// ssh users
	// Required: true
	SSHUsers []interface{} `json:"sshUsers"`
}

// Validate validates this Ssh users bulk operations request
func (m *SSHUsersBulkOperationsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSSHUsers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SSHUsersBulkOperationsRequest) validateSSHUsers(formats strfmt.Registry) error {

	if err := validate.Required("sshUsers", "body", m.SSHUsers); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SSHUsersBulkOperationsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SSHUsersBulkOperationsRequest) UnmarshalBinary(b []byte) error {
	var res SSHUsersBulkOperationsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
