// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SSHUserInfoDissociateResponse Ssh user info dissociate response
//
// swagger:model SshUserInfoDissociateResponse
type SSHUserInfoDissociateResponse struct {

	// true = the ssh user has been deleted since there are no more devices associated to this userfalse = the ssh user has not been deleted since some associations to devices exist.
	SSHUserDeleted bool `json:"sshUserDeleted,omitempty"`

	// ssh user to device association deleted
	SSHUserToDeviceAssociationDeleted bool `json:"sshUserToDeviceAssociationDeleted,omitempty"`
}

// Validate validates this Ssh user info dissociate response
func (m *SSHUserInfoDissociateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SSHUserInfoDissociateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SSHUserInfoDissociateResponse) UnmarshalBinary(b []byte) error {
	var res SSHUserInfoDissociateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
