// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SSHUserExists Ssh user exists
//
// swagger:model SshUserExists
type SSHUserExists struct {

	// metro code
	MetroCode string `json:"metroCode,omitempty"`

	// ssh username
	SSHUsername string `json:"sshUsername,omitempty"`
}

// Validate validates this Ssh user exists
func (m *SSHUserExists) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SSHUserExists) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SSHUserExists) UnmarshalBinary(b []byte) error {
	var res SSHUserExists
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
