// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SSHUserInfoVerbose Ssh user info verbose
//
// swagger:model SshUserInfoVerbose
type SSHUserInfoVerbose struct {

	// Set of uuids of the devices associated with this user
	DeviceUuids []string `json:"deviceUuids"`

	// Status and error messages corresponding to the metros this user exists on
	MetroStatusMap map[string]MetroStatus `json:"metroStatusMap,omitempty"`

	// Set of metros this user exists on
	Metros []string `json:"metros"`

	// username
	Username string `json:"username,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this Ssh user info verbose
func (m *SSHUserInfoVerbose) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetroStatusMap(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SSHUserInfoVerbose) validateMetroStatusMap(formats strfmt.Registry) error {

	if swag.IsZero(m.MetroStatusMap) { // not required
		return nil
	}

	for k := range m.MetroStatusMap {

		if err := validate.Required("metroStatusMap"+"."+k, "body", m.MetroStatusMap[k]); err != nil {
			return err
		}
		if val, ok := m.MetroStatusMap[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SSHUserInfoVerbose) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SSHUserInfoVerbose) UnmarshalBinary(b []byte) error {
	var res SSHUserInfoVerbose
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
