// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SSHUserCreateRequest Ssh user create request
//
// swagger:model SshUserCreateRequest
type SSHUserCreateRequest struct {

	// device Uuid
	// Required: true
	DeviceUUID *string `json:"deviceUuid"`

	// At least 6 and upto a maximum of 12 alphanumeric characters. The only special characters allowed are - _ $ @
	// Required: true
	Password *string `json:"password"`

	// At least 3 and upto a maximum of 32 alphanumeric characters. The only special characters allowed are - _
	// Required: true
	Username *string `json:"username"`
}

// Validate validates this Ssh user create request
func (m *SSHUserCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SSHUserCreateRequest) validateDeviceUUID(formats strfmt.Registry) error {

	if err := validate.Required("deviceUuid", "body", m.DeviceUUID); err != nil {
		return err
	}

	return nil
}

func (m *SSHUserCreateRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *SSHUserCreateRequest) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SSHUserCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SSHUserCreateRequest) UnmarshalBinary(b []byte) error {
	var res SSHUserCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
