// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Throughput throughput
//
// swagger:model Throughput
type Throughput struct {

	// throughput
	Throughput int32 `json:"throughput,omitempty"`

	// throughput unit
	ThroughputUnit string `json:"throughputUnit,omitempty"`
}

// Validate validates this throughput
func (m *Throughput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Throughput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Throughput) UnmarshalBinary(b []byte) error {
	var res Throughput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
