// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VendorConfig vendor config
//
// swagger:model VendorConfig
type VendorConfig struct {

	// Physical location within the Viptela overlay network, such as a branch office, or a campus (relevant only for Cisco SDWANs)
	SiteID string `json:"siteId,omitempty"`

	// IP assigned to CSRSDWAN router and vSmart controller (relevant only for Cisco SDWANs)
	SystemIPAddress string `json:"systemIpAddress,omitempty"`
}

// Validate validates this vendor config
func (m *VendorConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VendorConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VendorConfig) UnmarshalBinary(b []byte) error {
	var res VendorConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
