// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VirtualDeviceDetailsResponse virtual device details response
//
// swagger:model VirtualDeviceDetailsResponse
type VirtualDeviceDetailsResponse struct {

	// account name
	AccountName string `json:"accountName,omitempty"`

	// account number
	AccountNumber string `json:"accountNumber,omitempty"`

	// acl
	ACL []string `json:"acl"`

	// additional bandwidth
	AdditionalBandwidth int32 `json:"additionalBandwidth,omitempty"`

	// controller1
	Controller1 string `json:"controller1,omitempty"`

	// controller2
	Controller2 string `json:"controller2,omitempty"`

	// created by
	CreatedBy string `json:"createdBy,omitempty"`

	// created date
	CreatedDate string `json:"createdDate,omitempty"`

	// device serial no
	DeviceSerialNo string `json:"deviceSerialNo,omitempty"`

	// device type category
	DeviceTypeCategory string `json:"deviceTypeCategory,omitempty"`

	// device type code
	DeviceTypeCode string `json:"deviceTypeCode,omitempty"`

	// device type name
	DeviceTypeName string `json:"deviceTypeName,omitempty"`

	// device type vendor
	DeviceTypeVendor string `json:"deviceTypeVendor,omitempty"`

	// expiry
	Expiry string `json:"expiry,omitempty"`

	// host name
	HostName string `json:"hostName,omitempty"`

	// interfaces
	Interfaces []*InterfaceBasicInfoResponse `json:"interfaces"`

	// last updated by
	LastUpdatedBy string `json:"lastUpdatedBy,omitempty"`

	// last updated date
	LastUpdatedDate string `json:"lastUpdatedDate,omitempty"`

	// license file Id
	LicenseFileID string `json:"licenseFileId,omitempty"`

	// license key
	LicenseKey string `json:"licenseKey,omitempty"`

	// license name
	LicenseName string `json:"licenseName,omitempty"`

	// license secret
	LicenseSecret string `json:"licenseSecret,omitempty"`

	// license status
	LicenseStatus string `json:"licenseStatus,omitempty"`

	// license type
	LicenseType string `json:"licenseType,omitempty"`

	// local Id
	LocalID string `json:"localId,omitempty"`

	// management gateway Ip
	ManagementGatewayIP string `json:"managementGatewayIp,omitempty"`

	// management Ip
	ManagementIP string `json:"managementIp,omitempty"`

	// metro code
	MetroCode string `json:"metroCode,omitempty"`

	// metro name
	MetroName string `json:"metroName,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// notifications
	Notifications []string `json:"notifications"`

	// package code
	PackageCode string `json:"packageCode,omitempty"`

	// package name
	PackageName string `json:"packageName,omitempty"`

	// primary Dns name
	PrimaryDNSName string `json:"primaryDnsName,omitempty"`

	// public gateway Ip
	PublicGatewayIP string `json:"publicGatewayIp,omitempty"`

	// public Ip
	PublicIP string `json:"publicIp,omitempty"`

	// purchase order number
	PurchaseOrderNumber string `json:"purchaseOrderNumber,omitempty"`

	// redundancy type
	RedundancyType string `json:"redundancyType,omitempty"`

	// redundant UUID
	RedundantUUID string `json:"redundantUUID,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// remote Id
	RemoteID string `json:"remoteId,omitempty"`

	// secondary Dns name
	SecondaryDNSName string `json:"secondaryDnsName,omitempty"`

	// serial number
	SerialNumber string `json:"serialNumber,omitempty"`

	// site Id
	SiteID string `json:"siteId,omitempty"`

	// ssh Ip address
	SSHIPAddress string `json:"sshIpAddress,omitempty"`

	// ssh Ip fqdn
	SSHIPFqdn string `json:"sshIpFqdn,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// system Ip address
	SystemIPAddress string `json:"systemIpAddress,omitempty"`

	// term length
	TermLength int32 `json:"termLength,omitempty"`

	// throughput
	Throughput string `json:"throughput,omitempty"`

	// throughput unit
	ThroughputUnit string `json:"throughputUnit,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`

	// vendor config
	VendorConfig *VendorConfig `json:"vendorConfig,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this virtual device details response
func (m *VirtualDeviceDetailsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInterfaces(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVendorConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VirtualDeviceDetailsResponse) validateInterfaces(formats strfmt.Registry) error {

	if swag.IsZero(m.Interfaces) { // not required
		return nil
	}

	for i := 0; i < len(m.Interfaces); i++ {
		if swag.IsZero(m.Interfaces[i]) { // not required
			continue
		}

		if m.Interfaces[i] != nil {
			if err := m.Interfaces[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("interfaces" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VirtualDeviceDetailsResponse) validateVendorConfig(formats strfmt.Registry) error {

	if swag.IsZero(m.VendorConfig) { // not required
		return nil
	}

	if m.VendorConfig != nil {
		if err := m.VendorConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vendorConfig")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VirtualDeviceDetailsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirtualDeviceDetailsResponse) UnmarshalBinary(b []byte) error {
	var res VirtualDeviceDetailsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
