// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VirtualDeviceUpdateRequest virtual device update request
//
// swagger:model VirtualDeviceUpdateRequest
type VirtualDeviceUpdateRequest struct {

	// Virtual Device Name
	VirtualDeviceName string `json:"virtualDeviceName,omitempty"`
}

// Validate validates this virtual device update request
func (m *VirtualDeviceUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VirtualDeviceUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirtualDeviceUpdateRequest) UnmarshalBinary(b []byte) error {
	var res VirtualDeviceUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
