// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VirtualDeviceInternalPatchRequestDto virtual device internal patch request dto
//
// swagger:model VirtualDeviceInternalPatchRequestDto
type VirtualDeviceInternalPatchRequestDto struct {

	// notifications
	Notifications []string `json:"notifications"`

	// Term length in months. Please keep in mind that you cannot downgrade the term length.
	TermLength int64 `json:"termLength,omitempty"`

	// Virtual device name. This should be minimum 3 and maximum 50 characters long.
	VirtualDeviceName string `json:"virtualDeviceName,omitempty"`
}

// Validate validates this virtual device internal patch request dto
func (m *VirtualDeviceInternalPatchRequestDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VirtualDeviceInternalPatchRequestDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirtualDeviceInternalPatchRequestDto) UnmarshalBinary(b []byte) error {
	var res VirtualDeviceInternalPatchRequestDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
