// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VirtualDeviceCreateResponseDto virtual device create response dto
//
// swagger:model VirtualDeviceCreateResponseDto
type VirtualDeviceCreateResponseDto struct {

	// secondary UUID
	SecondaryUUID string `json:"secondaryUUID,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this virtual device create response dto
func (m *VirtualDeviceCreateResponseDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VirtualDeviceCreateResponseDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirtualDeviceCreateResponseDto) UnmarshalBinary(b []byte) error {
	var res VirtualDeviceCreateResponseDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
